### ISSUE TITLE
Running Training notebook

### ISSUE THREAD

**Issue by p-smirnov** [kekegg/DLEPS#1]
Hi!

I saw your article in Nature Biotech and was really interested in the model architecture you used and trying it on a different (much smaller) dataset. 

I tried to run the example training notebook, but I noticed that the h5 datasets are not available on the GitHub. I guess they may have been too big. Would you be able to share those files with me some other way so I can run the example notebook? 

Thank you in advance,
Petr

**Comment by Byronxy** [comment]
Hi!

I also met this error. The error message was:
```
Unable to open file (unable to open file: name = '../../data/vae.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**Comment by kekegg** [comment]
" vae.hdf5" can be found https://github.com/mkusner/grammarVAE/blob/master/pretrained/zinc_vae_grammar_L56_E100_val.hdf5.

**Comment by NEUISE** [comment]
您好：
        我在拜读您的文章并查看您的程序时，发现缺少一些文件，如训练集train_SMILES_demo.csv和测试集test_SMILES_demo.csv是如何获取的呢，如果方便的话是否可以发送到我的邮箱一下呢，621860496@qq.com。

> 感谢您百忙之中的查看并期望您的回复

**Comment by p-smirnov** [comment]
Could you also share: 

```
../../data/SMILE_train_demo.h5
../../data/SMILE_test_demo.h5
'../../data/RNA_train_demo.h5'
'../../data/RNA_test_demo.h5'
```
Or the weights file after training? 
``` 
'../../data/DLEPS_30000_tune_gvae10000.h5'
```

Right now Training.ipynb cannot run at all.

**Comment by tqinger** [comment]
> 你好！
> 
> 我在Nature Biotech上看到了您的文章，对您使用的模型架构非常感兴趣，并在不同的（小得多的）数据集上进行了尝试。
> 
> 我尝试运行示例训练笔记本，但我注意到 GitHub 上没有 h5 数据集。我想它们可能太大了。您是否能够以其他方式与我共享这些文件，以便我可以运行示例笔记本？
> 
> 提前谢谢你，彼得

Excuse me, can you run all files except train.py files?

**Comment by dreamfly999** [comment]
> Hi!
> 
> I saw your article in Nature Biotech and was really interested in the model architecture you used and trying it on a different (much smaller) dataset.
> 
> I tried to run the example training notebook, but I noticed that the h5 datasets are not available on the GitHub. I guess they may have been too big. Would you be able to share those files with me some other way so I can run the example notebook?
> 
> Thank you in advance, Petr

**Comment by Wenyuan-AI4science** [comment]
您好：
我在拜读您的文章并查看您的程序时，发现缺少一些文件，如训练集train_SMILES_demo.csv和测试集test_SMILES_demo.csv是如何获取的呢，如果方便的话是否可以发送到我的邮箱一下呢:liwy258@mail2.sysu.edu.cn
