### ISSUE TITLE
It is recommended that you do not try to reproduce, because it is a waste of time.

### ISSUE THREAD

**Issue by Ls94wood** [kekegg/DLEPS#10]
I've been through all issues,  found out that someone else had the same problem as me. I have to admit that this is a very valuable research framework, but the authors did not provide the key data files, nor did they describe how to access them, so when we took the time to create the same work environment, we still could not understand the algorithm from the source.

**Comment by barreettt** [comment]
I wish I had read this comment earlier.(╥╯^╰╥)
